steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'us-central1-docker.pkg.dev/kinetic-horizon-466218/live-cricket-tracker/live-cricket-tracker:$SHORT_SHA', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'us-central1-docker.pkg.dev/kinetic-horizon-466218/live-cricket-tracker/live-cricket-tracker:$SHORT_SHA']
- name: 'gcr.io/cloud-builders/gke-deploy'
  args:
    - run
    --filename=app.yaml
    --location=us-central1
    --cluster=autopilot-cluster-1
images:
- 'us-central1-docker.pkg.dev/kinetic-horizon-466218/live-cricket-tracker/live-cricket-tracker:$SHORT_SHA'
options:
  logging: CLOUD_LOGGING_ONLY
